n = input('Digite algo: ')
print('O tipo primitivo é: ', type(n))
print('Só tem espaço? ', n.isspace())
print('É um numerico? ', n.isnumeric())
print('É alfabético? ',n.isalpha())
print('É alfabanumérico? ', n.isalnum())
print('Está em maiúsculas? ', n.isupper())
print('Está em minúsculas? ', n.islower())
print('Está capitalizada? ', n.istitle())